### ISSUE TITLE
Deprecated selector in `atom-bracket-highlight/styles/index.atom-text-editor.less`

### ISSUE THREAD

**Issue by aphive** [pvorona/atom-bracket-highlight#5]
In `atom-bracket-highlight/styles/index.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .bracket-matcher .region` => `atom-text-editor.editor .bracket-matcher .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by packetspy** [comment]
Any news about this? Thanks!

**Comment by Emka877** [comment]
I don't think this is maintained anymore, last update 1 year ago.

**Comment by pvorona** [comment]
Hello guys, you probably should do a pr so i can merge and publish it.

**Comment by Emka877** [comment]
Latest update fixes it, ty :)

Can close this and #6 (dupe)
